(function (global) {
  var audit = global.ADMIN_SEED_SHARED.audit;

  function addr(id, memberId, type, extra) {
    return Object.assign(
      {
        id: id,
        member_user_id: memberId,
        type: type,
        member_type: "person",
        setting_prefix_id: null,
        name: null,
        store_name: null,
        tax_number: null,
        branch: null,
        branch_name: null,
        address: null,
        website_province_id: null,
        website_district_id: null,
        website_sub_district_id: null,
        postcode: null,
        tel: null,
        email: null,
        credit_limit: null,
        credit_date: null,
        relationship: null,
        is_same_information: false,
      },
      extra,
      audit(1)
    );
  }

  global.SEED_MEMBER_USER_ADDRESS = [
    addr(1, 1, "tax", {
      member_type: "person",
      setting_prefix_id: 1,
      name: "สมชาย ใจดี",
      tax_number: "1234567890123",
      address: "123 ถนนเจริญกรุง",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 1,
      postcode: "10200",
      tel: "081-2345678",
      email: "somchai@example.com",
      is_same_information: true,
    }),
    addr(2, 1, "doc", {
      member_type: "person",
      name: "สมชาย ใจดี",
      address: "123 ถนนเจริญกรุง",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 1,
      postcode: "10200",
      tel: "081-2345678",
      email: "somchai@example.com",
      is_same_information: true,
    }),
    addr(3, 1, "financial", {
      member_type: "person",
      name: "นภา ใจดี",
      address: "123 ถนนเจริญกรุง",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 1,
      postcode: "10200",
      tel: "081-9990000",
      credit_limit: 50000,
      credit_date: 30,
      relationship: "คู่สมรส",
    }),
    addr(4, 2, "tax", {
      member_type: "company",
      setting_prefix_id: 4,
      name: "อู่เจริญยนต์ จำกัด",
      store_name: "เจริญยนต์",
      tax_number: "0105551234567",
      branch: "headquarter",
      address: "88/9 ถนนพระราม 4",
      website_province_id: 1,
      website_district_id: 2,
      website_sub_district_id: 3,
      postcode: "10500",
      tel: "02-1234567",
      email: "info@charoenyon.co.th",
      is_same_information: true,
    }),
    addr(5, 2, "doc", {
      member_type: "company",
      name: "ฝ่ายบัญชี อู่เจริญยนต์",
      address: "88/9 ถนนพระราม 4",
      website_province_id: 1,
      website_district_id: 2,
      website_sub_district_id: 3,
      postcode: "10500",
      tel: "02-1234568",
      email: "docs@charoenyon.co.th",
    }),
    addr(6, 2, "financial", {
      member_type: "company",
      name: "วิรัช เจริญยนต์",
      address: "88/9 ถนนพระราม 4",
      website_province_id: 1,
      website_district_id: 2,
      website_sub_district_id: 3,
      postcode: "10500",
      tel: "081-2223344",
      credit_limit: 200000,
      credit_date: 45,
      relationship: "กรรมการ",
    }),
    addr(7, 3, "tax", {
      member_type: "person",
      setting_prefix_id: 3,
      name: "พิมพ์ รักดี",
      is_same_information: true,
      address: "15 ซอยสุขุมวิท 21",
      website_province_id: 1,
      website_district_id: 3,
      website_sub_district_id: 5,
      postcode: "10300",
      tel: "089-1112233",
      email: "pim@example.com",
    }),
    addr(8, 3, "doc", {
      member_type: "person",
      name: "พิมพ์ รักดี",
      is_same_information: true,
      address: "15 ซอยสุขุมวิท 21",
      website_province_id: 1,
      website_district_id: 3,
      website_sub_district_id: 5,
      postcode: "10300",
      tel: "089-1112233",
      email: "pim@example.com",
    }),
    addr(9, 3, "financial", {
      member_type: "person",
      name: "พิมพ์ รักดี",
      credit_limit: 10000,
      credit_date: 15,
      tel: "089-1112233",
    }),
    addr(10, 4, "tax", {
      member_type: "company",
      setting_prefix_id: 4,
      name: "บริษัท ออโต้พาร์ท จำกัด",
      tax_number: "0105567890123",
      branch: "branch",
      branch_name: "สาขาพระราม 2",
      is_same_information: true,
      address: "99 ถนนพระราม 2",
      website_province_id: 1,
      website_district_id: 4,
      website_sub_district_id: 7,
      postcode: "10900",
      tel: "02-9876543",
      email: "sales@autopart.co.th",
    }),
    addr(11, 4, "doc", {
      member_type: "company",
      name: "ฝ่ายจัดซื้อ ออโต้พาร์ท",
      address: "99 ถนนพระราม 2",
      website_province_id: 1,
      website_district_id: 4,
      website_sub_district_id: 7,
      postcode: "10900",
      tel: "02-9876544",
      email: "po@autopart.co.th",
    }),
    addr(12, 4, "financial", {
      member_type: "company",
      name: "กิตติ ออโต้",
      credit_limit: 500000,
      credit_date: 60,
      relationship: "ผู้จัดการ",
      tel: "081-7778888",
      address: "99 ถนนพระราม 2",
      website_province_id: 1,
      website_district_id: 4,
      website_sub_district_id: 7,
      postcode: "10900",
    }),
    addr(13, 5, "tax", {
      member_type: "person",
      setting_prefix_id: 1,
      name: "วิชัย มาใหม่",
      is_same_information: true,
      address: "42 ถนนเพชรบุรี",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 2,
      postcode: "10200",
      tel: "086-5556677",
      email: "wichai@example.com",
    }),
    addr(14, 5, "doc", {
      member_type: "person",
      name: "วิชัย มาใหม่",
      is_same_information: true,
      address: "42 ถนนเพชรบุรี",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 2,
      postcode: "10200",
      tel: "086-5556677",
      email: "wichai@example.com",
    }),
    addr(15, 5, "financial", {
      member_type: "person",
      name: "วิชัย มาใหม่",
      credit_limit: 20000,
      credit_date: 7,
      tel: "086-5556677",
    }),
  ];
})(window);
