(function (global) {
  var TS = global.ADMIN_SEED_SHARED.TS;
  global.SEED_SETTING_SALE_CHANNEL_LANGUAGE = [
    { setting_sale_channel_id: 1, locale: "th", name: "เว็บไซต์", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 1, locale: "en", name: "Website", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 2, locale: "th", name: "Shopee", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 2, locale: "en", name: "Shopee", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 3, locale: "th", name: "Lazada", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 3, locale: "en", name: "Lazada", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 4, locale: "th", name: "Facebook", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 4, locale: "en", name: "Facebook", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 5, locale: "th", name: "หน้าร้าน", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 5, locale: "en", name: "Walk-in", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 6, locale: "th", name: "อู่ · เงินสด · ราคาปลีก", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 6, locale: "en", name: "Garage · Cash · Retail", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 7, locale: "th", name: "อู่ · เงินสด · ราคาส่ง", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 7, locale: "en", name: "Garage · Cash · Wholesale", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 8, locale: "th", name: "อู่ · เงินเชื่อ · ราคาปลีก", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 8, locale: "en", name: "Garage · Credit · Retail", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 9, locale: "th", name: "อู่ · เงินเชื่อ · ราคาส่ง", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 9, locale: "en", name: "Garage · Credit · Wholesale", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 10, locale: "th", name: "ลูกค้าทั่วไป · เงินสด · ราคาปลีก", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 10, locale: "en", name: "General customer · Cash · Retail", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 11, locale: "th", name: "ลูกค้าทั่วไป · เงินสด · ราคาส่ง", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 11, locale: "en", name: "General customer · Cash · Wholesale", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 12, locale: "th", name: "ลูกค้าทั่วไป · เงินเชื่อ · ราคาปลีก", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 12, locale: "en", name: "General customer · Credit · Retail", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 13, locale: "th", name: "ลูกค้าทั่วไป · เงินเชื่อ · ราคาส่ง", created_at: TS, updated_at: TS },
    { setting_sale_channel_id: 13, locale: "en", name: "General customer · Credit · Wholesale", created_at: TS, updated_at: TS },
  ];
})(window);
