(function (global) {
  // ponytail: synthetic `id` for mock store; real PK is (supplier_user_id, type)
  global.SEED_SUPPLIER_INFORMATION = [
    {
      id: 1,
      supplier_user_id: 1,
      type: "contact",
      setting_prefix_id: 4,
      name: "อะไหล่รถยนต์ไทย",
      branch: "headquarter",
      branch_name: null,
      tax_number: "0105551234567",
      address: "123 ถนนพระราม 4 แขวงปทุมวัน",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 1,
      postcode: "10200",
      tel: "02-1234567",
      email: "info@thai-auto.test",
      is_same_information: false,
    },
    {
      id: 2,
      supplier_user_id: 1,
      type: "tax_invoice",
      setting_prefix_id: 4,
      name: "อะไหล่รถยนต์ไทย",
      branch: "headquarter",
      branch_name: null,
      tax_number: "0105551234567",
      address: "123 ถนนพระราม 4 แขวงปทุมวัน",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 1,
      postcode: "10200",
      tel: "02-1234567",
      email: "info@thai-auto.test",
      is_same_information: true,
    },
    {
      id: 3,
      supplier_user_id: 1,
      type: "delivery",
      setting_prefix_id: null,
      name: "ฝ่ายจัดส่ง อะไหล่รถยนต์ไทย",
      branch: null,
      branch_name: null,
      tax_number: null,
      address: "123 ถนนพระราม 4 แขวงปทุมวัน",
      website_province_id: 1,
      website_district_id: 1,
      website_sub_district_id: 1,
      postcode: "10200",
      tel: "02-1234568",
      email: null,
      is_same_information: false,
    },
    {
      id: 4,
      supplier_user_id: 2,
      type: "contact",
      setting_prefix_id: 5,
      name: "เชียงใหม่ ออโต้ พาร์ท",
      branch: "headquarter",
      branch_name: null,
      tax_number: "0105567890123",
      address: "88 ถนนมหิดล ตำบลสุเทพ",
      website_province_id: 9,
      website_district_id: 7,
      website_sub_district_id: 13,
      postcode: "50200",
      tel: "053-111222",
      email: "sales@cm-auto.test",
      is_same_information: false,
    },
    {
      id: 5,
      supplier_user_id: 2,
      type: "tax_invoice",
      setting_prefix_id: 5,
      name: "เชียงใหม่ ออโต้ พาร์ท",
      branch: "headquarter",
      branch_name: null,
      tax_number: "0105567890123",
      address: "88 ถนนมหิดล ตำบลสุเทพ",
      website_province_id: 9,
      website_district_id: 7,
      website_sub_district_id: 13,
      postcode: "50200",
      tel: "053-111222",
      email: "sales@cm-auto.test",
      is_same_information: true,
    },
    {
      id: 6,
      supplier_user_id: 2,
      type: "delivery",
      setting_prefix_id: null,
      name: "คุณสมศักดิ์ รับของ",
      branch: null,
      branch_name: null,
      tax_number: null,
      address: "88 ถนนมหิดล ตำบลสุเทพ",
      website_province_id: 9,
      website_district_id: 7,
      website_sub_district_id: 13,
      postcode: "50200",
      tel: "081-2345678",
      email: null,
      is_same_information: false,
    },
    {
      id: 7,
      supplier_user_id: 3,
      type: "contact",
      setting_prefix_id: 7,
      name: "สมชาย อะไหล่รถ",
      branch: null,
      branch_name: null,
      tax_number: "1234567890123",
      address: "45/1 ถ. อโศก",
      website_province_id: 1,
      website_district_id: 2,
      website_sub_district_id: 3,
      postcode: "10500",
      tel: "089-8887777",
      email: "somchai@parts.test",
      is_same_information: false,
    },
    {
      id: 8,
      supplier_user_id: 3,
      type: "tax_invoice",
      setting_prefix_id: 7,
      name: "สมชาย อะไหล่รถ",
      branch: null,
      branch_name: null,
      tax_number: "1234567890123",
      address: "45/1 ถ. อโศก",
      website_province_id: 1,
      website_district_id: 2,
      website_sub_district_id: 3,
      postcode: "10500",
      tel: "089-8887777",
      email: "somchai@parts.test",
      is_same_information: true,
    },
    {
      id: 9,
      supplier_user_id: 3,
      type: "delivery",
      setting_prefix_id: null,
      name: "สมชาย อะไหล่รถ",
      branch: null,
      branch_name: null,
      tax_number: null,
      address: "45/1 ถ. อโศก",
      website_province_id: 1,
      website_district_id: 2,
      website_sub_district_id: 3,
      postcode: "10500",
      tel: "089-8887777",
      email: null,
      is_same_information: false,
    },
    {
      id: 10,
      supplier_user_id: 4,
      type: "contact",
      setting_prefix_id: 6,
      name: "ห้างหุ้นส่วนจำกัด ภูเก็ต มอเตอร์",
      branch: "branch",
      branch_name: "สาขาภูเก็ต",
      tax_number: "0105576543210",
      address: "12 ถนนรัษฎา",
      website_province_id: 11,
      website_district_id: 10,
      website_sub_district_id: 19,
      postcode: "83000",
      tel: "076-555666",
      email: "contact@phuket-motor.test",
      is_same_information: false,
    },
    {
      id: 11,
      supplier_user_id: 4,
      type: "tax_invoice",
      setting_prefix_id: 6,
      name: "ห้างหุ้นส่วนจำกัด ภูเก็ต มอเตอร์",
      branch: "branch",
      branch_name: "สาขาภูเก็ต",
      tax_number: "0105576543210",
      address: "12 ถนนรัษฎา",
      website_province_id: 11,
      website_district_id: 10,
      website_sub_district_id: 19,
      postcode: "83000",
      tel: "076-555666",
      email: "contact@phuket-motor.test",
      is_same_information: false,
    },
    {
      id: 12,
      supplier_user_id: 4,
      type: "delivery",
      setting_prefix_id: null,
      name: "ฝ่ายคลัง ภูเก็ต มอเตอร์",
      branch: null,
      branch_name: null,
      tax_number: null,
      address: "12 ถนนรัษฎา",
      website_province_id: 11,
      website_district_id: 10,
      website_sub_district_id: 19,
      postcode: "83000",
      tel: "076-555667",
      email: null,
      is_same_information: false,
    },
  ];
})(window);
