(function (global) {
  var TS = global.ADMIN_SEED_SHARED.TS;
  global.SEED_SYSTEM_DISTRICT_LANGUAGE = [
    { system_district_id: 1, locale: "th", name: "พระนคร", created_at: TS, updated_at: TS },
    { system_district_id: 1, locale: "en", name: "Phra Nakhon", created_at: TS, updated_at: TS },
    { system_district_id: 2, locale: "th", name: "บางรัก", created_at: TS, updated_at: TS },
    { system_district_id: 2, locale: "en", name: "Bang Rak", created_at: TS, updated_at: TS },
    { system_district_id: 3, locale: "th", name: "ดุสิต", created_at: TS, updated_at: TS },
    { system_district_id: 3, locale: "en", name: "Dusit", created_at: TS, updated_at: TS },
    { system_district_id: 4, locale: "th", name: "จตุจักร", created_at: TS, updated_at: TS },
    { system_district_id: 4, locale: "en", name: "Chatuchak", created_at: TS, updated_at: TS },
    { system_district_id: 5, locale: "th", name: "เมืองนนทบุรี", created_at: TS, updated_at: TS },
    { system_district_id: 5, locale: "en", name: "Mueang Nonthaburi", created_at: TS, updated_at: TS },
    { system_district_id: 6, locale: "th", name: "ปากเกร็ด", created_at: TS, updated_at: TS },
    { system_district_id: 6, locale: "en", name: "Pak Kret", created_at: TS, updated_at: TS },
    { system_district_id: 7, locale: "th", name: "เมืองเชียงใหม่", created_at: TS, updated_at: TS },
    { system_district_id: 7, locale: "en", name: "Mueang Chiang Mai", created_at: TS, updated_at: TS },
    { system_district_id: 8, locale: "th", name: "แม่ริม", created_at: TS, updated_at: TS },
    { system_district_id: 8, locale: "en", name: "Mae Rim", created_at: TS, updated_at: TS },
    { system_district_id: 9, locale: "th", name: "สันทราย", created_at: TS, updated_at: TS },
    { system_district_id: 9, locale: "en", name: "San Sai", created_at: TS, updated_at: TS },
    { system_district_id: 10, locale: "th", name: "เมืองภูเก็ต", created_at: TS, updated_at: TS },
    { system_district_id: 10, locale: "en", name: "Mueang Phuket", created_at: TS, updated_at: TS },
    { system_district_id: 11, locale: "th", name: "กะทู้", created_at: TS, updated_at: TS },
    { system_district_id: 11, locale: "en", name: "Kathu", created_at: TS, updated_at: TS },
    { system_district_id: 12, locale: "th", name: "เมืองชลบุรี", created_at: TS, updated_at: TS },
    { system_district_id: 12, locale: "en", name: "Mueang Chon Buri", created_at: TS, updated_at: TS },
    { system_district_id: 13, locale: "th", name: "บางแสน", created_at: TS, updated_at: TS },
    { system_district_id: 13, locale: "en", name: "Bang Saen", created_at: TS, updated_at: TS },
    { system_district_id: 14, locale: "th", name: "กลาง", created_at: TS, updated_at: TS },
    { system_district_id: 14, locale: "en", name: "Central", created_at: TS, updated_at: TS },
    { system_district_id: 15, locale: "th", name: "ตะวันออก", created_at: TS, updated_at: TS },
    { system_district_id: 15, locale: "en", name: "East", created_at: TS, updated_at: TS },
  ];
})(window);
