(function (global) {
  var TS = global.ADMIN_SEED_SHARED.TS;
  global.SEED_WAREHOUSE_LIST_LANGUAGE = [
    { warehouse_list_id: 1, locale: "th", name: "ATW", created_at: TS, updated_at: TS },
    { warehouse_list_id: 1, locale: "en", name: "ATW", created_at: TS, updated_at: TS },
    { warehouse_list_id: 2, locale: "th", name: "PJB", created_at: TS, updated_at: TS },
    { warehouse_list_id: 2, locale: "en", name: "PJB", created_at: TS, updated_at: TS },
    { warehouse_list_id: 3, locale: "th", name: "GS", created_at: TS, updated_at: TS },
    { warehouse_list_id: 3, locale: "en", name: "GS", created_at: TS, updated_at: TS },
    { warehouse_list_id: 4, locale: "th", name: "โซน 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 4, locale: "en", name: "Zone 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 5, locale: "th", name: "โซน 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 5, locale: "en", name: "Zone 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 6, locale: "th", name: "โซน 3", created_at: TS, updated_at: TS },
    { warehouse_list_id: 6, locale: "en", name: "Zone 3", created_at: TS, updated_at: TS },
    { warehouse_list_id: 7, locale: "th", name: "โซน 4", created_at: TS, updated_at: TS },
    { warehouse_list_id: 7, locale: "en", name: "Zone 4", created_at: TS, updated_at: TS },
    { warehouse_list_id: 8, locale: "th", name: "โซน 5", created_at: TS, updated_at: TS },
    { warehouse_list_id: 8, locale: "en", name: "Zone 5", created_at: TS, updated_at: TS },
    { warehouse_list_id: 9, locale: "th", name: "โซน 6", created_at: TS, updated_at: TS },
    { warehouse_list_id: 9, locale: "en", name: "Zone 6", created_at: TS, updated_at: TS },
    { warehouse_list_id: 10, locale: "th", name: "โซน 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 10, locale: "en", name: "Zone 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 11, locale: "th", name: "โซน 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 11, locale: "en", name: "Zone 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 12, locale: "th", name: "โซน 3", created_at: TS, updated_at: TS },
    { warehouse_list_id: 12, locale: "en", name: "Zone 3", created_at: TS, updated_at: TS },
    { warehouse_list_id: 13, locale: "th", name: "โซน 4", created_at: TS, updated_at: TS },
    { warehouse_list_id: 13, locale: "en", name: "Zone 4", created_at: TS, updated_at: TS },
    { warehouse_list_id: 14, locale: "th", name: "โซน 5", created_at: TS, updated_at: TS },
    { warehouse_list_id: 14, locale: "en", name: "Zone 5", created_at: TS, updated_at: TS },
    { warehouse_list_id: 15, locale: "th", name: "โซน 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 15, locale: "en", name: "Zone 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 16, locale: "th", name: "โซน 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 16, locale: "en", name: "Zone 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 17, locale: "th", name: "โซน 3", created_at: TS, updated_at: TS },
    { warehouse_list_id: 17, locale: "en", name: "Zone 3", created_at: TS, updated_at: TS },
    { warehouse_list_id: 18, locale: "th", name: "โซน 4", created_at: TS, updated_at: TS },
    { warehouse_list_id: 18, locale: "en", name: "Zone 4", created_at: TS, updated_at: TS },
    { warehouse_list_id: 19, locale: "th", name: "ชั้นวาง 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 19, locale: "en", name: "Shelf 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 20, locale: "th", name: "ชั้นวาง 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 20, locale: "en", name: "Shelf 2", created_at: TS, updated_at: TS },
    { warehouse_list_id: 21, locale: "th", name: "แร็ค 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 21, locale: "en", name: "Rack 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 22, locale: "th", name: "กล่อง 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 22, locale: "en", name: "Bin 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 23, locale: "th", name: "ชั้นวาง 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 23, locale: "en", name: "Shelf 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 24, locale: "th", name: "แร็ค 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 24, locale: "en", name: "Rack 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 25, locale: "th", name: "กล่อง 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 25, locale: "en", name: "Bin 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 26, locale: "th", name: "ชั้นวาง 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 26, locale: "en", name: "Shelf 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 27, locale: "th", name: "แร็ค 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 27, locale: "en", name: "Rack 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 28, locale: "th", name: "กล่อง 1", created_at: TS, updated_at: TS },
    { warehouse_list_id: 28, locale: "en", name: "Bin 1", created_at: TS, updated_at: TS },
  ];
})(window);
