(function (global) {
  var TS = global.ADMIN_SEED_SHARED.TS;
  global.SEED_WEBSITE_SUB_DISTRICT_LANGUAGE = [
    { website_sub_district_id: 1, locale: "th", name: "พระบรมมหาราชวัง", created_at: TS, updated_at: TS },
    { website_sub_district_id: 1, locale: "en", name: "Phra Borom Maha Ratchawang", created_at: TS, updated_at: TS },
    { website_sub_district_id: 2, locale: "th", name: "วัดสามพระยา", created_at: TS, updated_at: TS },
    { website_sub_district_id: 2, locale: "en", name: "Wat Sam Phraya", created_at: TS, updated_at: TS },
    { website_sub_district_id: 3, locale: "th", name: "สีลม", created_at: TS, updated_at: TS },
    { website_sub_district_id: 3, locale: "en", name: "Silom", created_at: TS, updated_at: TS },
    { website_sub_district_id: 4, locale: "th", name: "สุริยวงศ์", created_at: TS, updated_at: TS },
    { website_sub_district_id: 4, locale: "en", name: "Suriyawong", created_at: TS, updated_at: TS },
    { website_sub_district_id: 5, locale: "th", name: "ดุสิต", created_at: TS, updated_at: TS },
    { website_sub_district_id: 5, locale: "en", name: "Dusit", created_at: TS, updated_at: TS },
    { website_sub_district_id: 6, locale: "th", name: "วชิรพยาบาล", created_at: TS, updated_at: TS },
    { website_sub_district_id: 6, locale: "en", name: "Wachiraphayaban", created_at: TS, updated_at: TS },
    { website_sub_district_id: 7, locale: "th", name: "จตุจักร", created_at: TS, updated_at: TS },
    { website_sub_district_id: 7, locale: "en", name: "Chatuchak", created_at: TS, updated_at: TS },
    { website_sub_district_id: 8, locale: "th", name: "ลาดยาว", created_at: TS, updated_at: TS },
    { website_sub_district_id: 8, locale: "en", name: "Lat Yao", created_at: TS, updated_at: TS },
    { website_sub_district_id: 9, locale: "th", name: "สวนใหญ่", created_at: TS, updated_at: TS },
    { website_sub_district_id: 9, locale: "en", name: "Suan Yai", created_at: TS, updated_at: TS },
    { website_sub_district_id: 10, locale: "th", name: "ตลาดขวัญ", created_at: TS, updated_at: TS },
    { website_sub_district_id: 10, locale: "en", name: "Talat Khwan", created_at: TS, updated_at: TS },
    { website_sub_district_id: 11, locale: "th", name: "ปากเกร็ด", created_at: TS, updated_at: TS },
    { website_sub_district_id: 11, locale: "en", name: "Pak Kret", created_at: TS, updated_at: TS },
    { website_sub_district_id: 12, locale: "th", name: "บางตลาด", created_at: TS, updated_at: TS },
    { website_sub_district_id: 12, locale: "en", name: "Bang Talat", created_at: TS, updated_at: TS },
    { website_sub_district_id: 13, locale: "th", name: "ศรีภูมิ", created_at: TS, updated_at: TS },
    { website_sub_district_id: 13, locale: "en", name: "Si Phum", created_at: TS, updated_at: TS },
    { website_sub_district_id: 14, locale: "th", name: "พระสิงห์", created_at: TS, updated_at: TS },
    { website_sub_district_id: 14, locale: "en", name: "Phra Sing", created_at: TS, updated_at: TS },
    { website_sub_district_id: 15, locale: "th", name: "แม่ริม", created_at: TS, updated_at: TS },
    { website_sub_district_id: 15, locale: "en", name: "Mae Rim", created_at: TS, updated_at: TS },
    { website_sub_district_id: 16, locale: "th", name: "ริมเหนือ", created_at: TS, updated_at: TS },
    { website_sub_district_id: 16, locale: "en", name: "Rim Nuea", created_at: TS, updated_at: TS },
    { website_sub_district_id: 17, locale: "th", name: "สันทรายน้อย", created_at: TS, updated_at: TS },
    { website_sub_district_id: 17, locale: "en", name: "San Sai Noi", created_at: TS, updated_at: TS },
    { website_sub_district_id: 18, locale: "th", name: "สันผีเสื้อ", created_at: TS, updated_at: TS },
    { website_sub_district_id: 18, locale: "en", name: "San Phisuek", created_at: TS, updated_at: TS },
    { website_sub_district_id: 19, locale: "th", name: "ตลาดใหญ่", created_at: TS, updated_at: TS },
    { website_sub_district_id: 19, locale: "en", name: "Talat Yai", created_at: TS, updated_at: TS },
    { website_sub_district_id: 20, locale: "th", name: "ตลาดเหนือ", created_at: TS, updated_at: TS },
    { website_sub_district_id: 20, locale: "en", name: "Talat Nuea", created_at: TS, updated_at: TS },
    { website_sub_district_id: 21, locale: "th", name: "กะทู้", created_at: TS, updated_at: TS },
    { website_sub_district_id: 21, locale: "en", name: "Kathu", created_at: TS, updated_at: TS },
    { website_sub_district_id: 22, locale: "th", name: "กมลา", created_at: TS, updated_at: TS },
    { website_sub_district_id: 22, locale: "en", name: "Kamala", created_at: TS, updated_at: TS },
    { website_sub_district_id: 23, locale: "th", name: "บางปลาสร้อย", created_at: TS, updated_at: TS },
    { website_sub_district_id: 23, locale: "en", name: "Bang Pla Soi", created_at: TS, updated_at: TS },
    { website_sub_district_id: 24, locale: "th", name: "แสนสุข", created_at: TS, updated_at: TS },
    { website_sub_district_id: 24, locale: "en", name: "Saen Suk", created_at: TS, updated_at: TS },
    { website_sub_district_id: 25, locale: "th", name: "บางแสน", created_at: TS, updated_at: TS },
    { website_sub_district_id: 25, locale: "en", name: "Bang Saen", created_at: TS, updated_at: TS },
    { website_sub_district_id: 26, locale: "th", name: "แสนสุข", created_at: TS, updated_at: TS },
    { website_sub_district_id: 26, locale: "en", name: "Saen Suk", created_at: TS, updated_at: TS },
    { website_sub_district_id: 27, locale: "th", name: "ดาวน์ทาวน์", created_at: TS, updated_at: TS },
    { website_sub_district_id: 27, locale: "en", name: "Downtown Core", created_at: TS, updated_at: TS },
    { website_sub_district_id: 28, locale: "th", name: "ออร์ชาร์ด", created_at: TS, updated_at: TS },
    { website_sub_district_id: 28, locale: "en", name: "Orchard", created_at: TS, updated_at: TS },
    { website_sub_district_id: 29, locale: "th", name: "เบโดก", created_at: TS, updated_at: TS },
    { website_sub_district_id: 29, locale: "en", name: "Bedok", created_at: TS, updated_at: TS },
    { website_sub_district_id: 30, locale: "th", name: "แทมไพน์", created_at: TS, updated_at: TS },
    { website_sub_district_id: 30, locale: "en", name: "Tampines", created_at: TS, updated_at: TS },
  ];
})(window);
