(function (global) {
  var TS = global.ADMIN_SEED_SHARED.TS;
  global.SEED_WEBSITE_PROVINCE_LANGUAGE = [
    { website_province_id: 1, locale: "th", name: "กรุงเทพมหานคร", created_at: TS, updated_at: TS },
    { website_province_id: 1, locale: "en", name: "Bangkok", created_at: TS, updated_at: TS },
    { website_province_id: 2, locale: "th", name: "สมุทรปราการ", created_at: TS, updated_at: TS },
    { website_province_id: 2, locale: "en", name: "Samut Prakan", created_at: TS, updated_at: TS },
    { website_province_id: 3, locale: "th", name: "นนทบุรี", created_at: TS, updated_at: TS },
    { website_province_id: 3, locale: "en", name: "Nonthaburi", created_at: TS, updated_at: TS },
    { website_province_id: 4, locale: "th", name: "ปทุมธานี", created_at: TS, updated_at: TS },
    { website_province_id: 4, locale: "en", name: "Pathum Thani", created_at: TS, updated_at: TS },
    { website_province_id: 5, locale: "th", name: "ชลบุรี", created_at: TS, updated_at: TS },
    { website_province_id: 5, locale: "en", name: "Chon Buri", created_at: TS, updated_at: TS },
    { website_province_id: 6, locale: "th", name: "ระยอง", created_at: TS, updated_at: TS },
    { website_province_id: 6, locale: "en", name: "Rayong", created_at: TS, updated_at: TS },
    { website_province_id: 7, locale: "th", name: "นครราชสีมา", created_at: TS, updated_at: TS },
    { website_province_id: 7, locale: "en", name: "Nakhon Ratchasima", created_at: TS, updated_at: TS },
    { website_province_id: 8, locale: "th", name: "ขอนแก่น", created_at: TS, updated_at: TS },
    { website_province_id: 8, locale: "en", name: "Khon Kaen", created_at: TS, updated_at: TS },
    { website_province_id: 9, locale: "th", name: "เชียงใหม่", created_at: TS, updated_at: TS },
    { website_province_id: 9, locale: "en", name: "Chiang Mai", created_at: TS, updated_at: TS },
    { website_province_id: 10, locale: "th", name: "เชียงราย", created_at: TS, updated_at: TS },
    { website_province_id: 10, locale: "en", name: "Chiang Rai", created_at: TS, updated_at: TS },
    { website_province_id: 11, locale: "th", name: "ภูเก็ต", created_at: TS, updated_at: TS },
    { website_province_id: 11, locale: "en", name: "Phuket", created_at: TS, updated_at: TS },
    { website_province_id: 12, locale: "th", name: "สงขลา", created_at: TS, updated_at: TS },
    { website_province_id: 12, locale: "en", name: "Songkhla", created_at: TS, updated_at: TS },
    { website_province_id: 13, locale: "th", name: "สิงคโปร์", created_at: TS, updated_at: TS },
    { website_province_id: 13, locale: "en", name: "Singapore", created_at: TS, updated_at: TS },
  ];
})(window);
