-- +goose Up
-- +goose StatementBegin
CREATE TYPE order_quotation_status AS ENUM (
    'draft',
    'pending',
    'approved',
    'success',
    'cancelled',
    'rejected'
);

CREATE TYPE order_quotation_accept_mode AS ENUM ('payment', 'credit');

CREATE TABLE order_quotation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT,
    status order_quotation_status NOT NULL DEFAULT 'draft',
    member_user_id BIGINT REFERENCES member_user(id) ON DELETE SET NULL,
    member_setting_credit_id BIGINT REFERENCES member_setting_credit(id) ON DELETE SET NULL,
    member_name TEXT,
    member_tel TEXT,
    member_email TEXT,
    issue_date DATE,
    valid_until DATE,
    reserve_stock BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    accept_mode order_quotation_accept_mode,
    accepted_at TIMESTAMPTZ,
    credit_date DATE,
    vat_type setting_vat_type NOT NULL DEFAULT 'exclude',
    vat_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    subtotal_ex_vat NUMERIC(15,4) NOT NULL DEFAULT 0,
    discount_total NUMERIC(15,4) NOT NULL DEFAULT 0,
    vat_amount NUMERIC(15,4) NOT NULL DEFAULT 0,
    grand_total NUMERIC(15,4) NOT NULL DEFAULT 0,
    parent_id BIGINT REFERENCES order_quotation(id) ON DELETE SET NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    CONSTRAINT uq_order_quotation_sku UNIQUE (sku)
);

CREATE INDEX idx_order_quotation_status ON order_quotation (status) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_quotation_member ON order_quotation (member_user_id) WHERE member_user_id IS NOT NULL;
CREATE INDEX idx_order_quotation_valid_until ON order_quotation (valid_until) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_quotation_created_by ON order_quotation (created_by) WHERE created_by IS NOT NULL;
CREATE INDEX idx_order_quotation_created_at ON order_quotation (created_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_quotation_parent ON order_quotation (parent_id) WHERE parent_id IS NOT NULL;

CREATE TABLE order_quotation_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_quotation_id BIGINT NOT NULL REFERENCES order_quotation(id) ON DELETE CASCADE,
    product_item_id BIGINT REFERENCES product_item(id) ON DELETE SET NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    amount NUMERIC(15,4) NOT NULL DEFAULT 0,
    price_per_unit NUMERIC(15,4) NOT NULL DEFAULT 0,
    discount NUMERIC(15,4) NOT NULL DEFAULT 0,
    vat_type setting_vat_type NOT NULL DEFAULT 'exclude',
    vat_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    total_price NUMERIC(15,4) NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL
);

CREATE INDEX idx_order_quotation_item_quote ON order_quotation_item (order_quotation_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_quotation_item_product ON order_quotation_item (product_item_id) WHERE product_item_id IS NOT NULL;
CREATE INDEX idx_order_quotation_item_sort ON order_quotation_item (order_quotation_id, sort_order) WHERE deleted_at IS NULL;

CREATE TABLE order_quotation_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_quotation_id BIGINT NOT NULL REFERENCES order_quotation(id) ON DELETE CASCADE,
    system_file_id BIGINT NOT NULL REFERENCES system_file(id) ON DELETE RESTRICT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_order_quotation_file_quote_file
    ON order_quotation_file (order_quotation_id, system_file_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_order_quotation_file_quote_sort
    ON order_quotation_file (order_quotation_id, sort_order)
    WHERE deleted_at IS NULL;

ALTER TABLE order_list
    ADD COLUMN order_quotation_id BIGINT REFERENCES order_quotation(id) ON DELETE SET NULL;

CREATE INDEX idx_order_list_order_quotation
    ON order_list (order_quotation_id) WHERE order_quotation_id IS NOT NULL;

ALTER TABLE order_payment
    ADD COLUMN order_quotation_id BIGINT REFERENCES order_quotation(id) ON DELETE SET NULL;

CREATE INDEX idx_order_payment_order_quotation
    ON order_payment (order_quotation_id) WHERE order_quotation_id IS NOT NULL;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_order_payment_order_quotation;
ALTER TABLE order_payment DROP COLUMN IF EXISTS order_quotation_id;

DROP INDEX IF EXISTS idx_order_list_order_quotation;
ALTER TABLE order_list DROP COLUMN IF EXISTS order_quotation_id;

DROP TABLE IF EXISTS order_quotation_file CASCADE;
DROP TABLE IF EXISTS order_quotation_item CASCADE;
DROP TABLE IF EXISTS order_quotation CASCADE;

DROP TYPE IF EXISTS order_quotation_accept_mode;
DROP TYPE IF EXISTS order_quotation_status;
-- +goose StatementEnd
