-- +goose Up
-- +goose StatementBegin
CREATE TYPE order_list_status AS ENUM ('draft', 'pending', 'success', 'cancelled', 'rejected');
CREATE TYPE order_list_fulfill_status AS ENUM ('pending', 'in_progress', 'success', 'fail');
CREATE TYPE order_list_item_status AS ENUM ('pending', 'in_progress', 'success');
CREATE TYPE order_list_item_type AS ENUM ('item', 'compare');
CREATE TYPE order_shipping_type AS ENUM ('store', 'parking', 'delivery');
CREATE TYPE order_list_print_kind AS ENUM ('picking_slip');
CREATE TYPE order_payment_category AS ENUM ('credit', 'payment');
CREATE TYPE order_claim_payment_type AS ENUM ('cash', 'transfer', 'other', 'debt_reduction');
CREATE TYPE order_claim_status AS ENUM (
    'pending', 'acknowledged', 'waiting_supplier', 'success', 'cancelled', 'rejected'
);

CREATE TABLE order_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT,
    status order_list_status NOT NULL DEFAULT 'draft',
    fulfill_status order_list_fulfill_status NOT NULL DEFAULT 'pending',
    parent_id BIGINT REFERENCES order_list(id) ON DELETE SET NULL,
    member_user_id BIGINT REFERENCES member_user(id) ON DELETE SET NULL,
    member_setting_credit_id BIGINT REFERENCES member_setting_credit(id) ON DELETE SET NULL,
    member_name TEXT,
    member_tel TEXT,
    member_email TEXT,
    ordered_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    CONSTRAINT uq_order_list_sku UNIQUE (sku)
);

CREATE INDEX idx_order_list_status ON order_list (status) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_list_fulfill ON order_list (fulfill_status) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_list_member ON order_list (member_user_id) WHERE member_user_id IS NOT NULL;
CREATE INDEX idx_order_list_member_setting_credit ON order_list (member_setting_credit_id) WHERE member_setting_credit_id IS NOT NULL;
CREATE INDEX idx_order_list_parent ON order_list (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX idx_order_list_created_by ON order_list (created_by) WHERE created_by IS NOT NULL;

CREATE TABLE order_list_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_list_id BIGINT NOT NULL REFERENCES order_list(id) ON DELETE CASCADE,
    product_item_id BIGINT REFERENCES product_item(id) ON DELETE SET NULL,
    type order_list_item_type NOT NULL DEFAULT 'item',
    amount NUMERIC(15,4) NOT NULL DEFAULT 0,
    amount_picked NUMERIC(15,4) NOT NULL DEFAULT 0,
    amount_checked NUMERIC(15,4) NOT NULL DEFAULT 0,
    status order_list_item_status NOT NULL DEFAULT 'pending',
    price_per_unit NUMERIC(15,4) NOT NULL DEFAULT 0,
    discount NUMERIC(15,4) NOT NULL DEFAULT 0,
    total_price NUMERIC(15,4) NOT NULL DEFAULT 0,
    detail JSONB,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL
);

CREATE INDEX idx_order_list_item_order ON order_list_item (order_list_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_order_list_item_product ON order_list_item (product_item_id) WHERE product_item_id IS NOT NULL;

CREATE TABLE order_list_item_warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_list_item_id BIGINT NOT NULL REFERENCES order_list_item(id) ON DELETE CASCADE,
    warehouse_list_id BIGINT NOT NULL REFERENCES warehouse_list(id) ON DELETE RESTRICT,
    amount_checked NUMERIC(15,4) NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_order_list_item_warehouse_item_location
    ON order_list_item_warehouse (order_list_item_id, warehouse_list_id) WHERE deleted_at IS NULL;

CREATE TABLE order_shipping (
    order_list_id BIGINT NOT NULL REFERENCES order_list(id) ON DELETE CASCADE,
    type order_shipping_type NOT NULL DEFAULT 'store',
    received_at TIMESTAMPTZ,
    PRIMARY KEY (order_list_id)
);

CREATE TABLE order_list_print_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_list_id BIGINT NOT NULL REFERENCES order_list(id) ON DELETE CASCADE,
    kind order_list_print_kind NOT NULL DEFAULT 'picking_slip',
    printed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    printed_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL
);

CREATE INDEX idx_order_list_print_log_order ON order_list_print_log (order_list_id, printed_at DESC);

CREATE TABLE order_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_list_id BIGINT NOT NULL REFERENCES order_list(id) ON DELETE CASCADE,
    sku TEXT,
    payment_category order_payment_category NOT NULL,
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vat_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount NUMERIC(15,4) NOT NULL DEFAULT 0,
    special_discount NUMERIC(15,4) NOT NULL DEFAULT 0,
    total_price NUMERIC(15,4) NOT NULL DEFAULT 0,
    amount_paid NUMERIC(15,4) NOT NULL DEFAULT 0,
    is_full BOOLEAN GENERATED ALWAYS AS (amount_paid >= total_price) STORED,
    is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    credit_approved_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    discount_approved_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    CONSTRAINT uq_order_payment_sku UNIQUE (sku)
);

CREATE INDEX idx_order_payment_order ON order_payment (order_list_id) WHERE deleted_at IS NULL;

CREATE TABLE order_payment_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_payment_id BIGINT NOT NULL REFERENCES order_payment(id) ON DELETE CASCADE,
    order_list_item_id BIGINT NOT NULL REFERENCES order_list_item(id) ON DELETE RESTRICT,
    amount NUMERIC(15,4) NOT NULL DEFAULT 0,
    vat_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    price_per_unit NUMERIC(15,4) NOT NULL DEFAULT 0,
    discount NUMERIC(15,4) NOT NULL DEFAULT 0,
    total_price NUMERIC(15,4) NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    CONSTRAINT uq_order_payment_item_payment_order_item UNIQUE (order_payment_id, order_list_item_id)
);

CREATE TABLE order_payment_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_payment_id BIGINT NOT NULL REFERENCES order_payment(id) ON DELETE CASCADE,
    setting_payment_method_id BIGINT NOT NULL REFERENCES setting_payment_method(id) ON DELETE RESTRICT,
    amount NUMERIC(15,4) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_order_payment_method_payment_setting
    ON order_payment_method (order_payment_id, setting_payment_method_id) WHERE deleted_at IS NULL;

CREATE TABLE order_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT,
    order_payment_id BIGINT NOT NULL REFERENCES order_payment(id) ON DELETE RESTRICT,
    supplier_user_id BIGINT REFERENCES supplier_user(id) ON DELETE SET NULL,
    type claim_type NOT NULL,
    payment_type order_claim_payment_type NOT NULL,
    other_reason TEXT NOT NULL DEFAULT '',
    total_price NUMERIC(15,4) NOT NULL DEFAULT 0,
    status order_claim_status NOT NULL DEFAULT 'pending',
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    CONSTRAINT uq_order_claim_sku UNIQUE (sku)
);

UPDATE system_code_prefix SET code_key = 'order_list' WHERE code_key = 'order_order';

CREATE TABLE order_claim_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_claim_id BIGINT NOT NULL REFERENCES order_claim(id) ON DELETE CASCADE,
    order_payment_item_id BIGINT NOT NULL REFERENCES order_payment_item(id) ON DELETE RESTRICT,
    setting_claim_reason_id BIGINT NOT NULL REFERENCES setting_claim_reason(id) ON DELETE RESTRICT,
    type claim_type NOT NULL,
    amount NUMERIC(15,4) NOT NULL DEFAULT 0,
    status order_claim_status NOT NULL DEFAULT 'pending',
    note TEXT NOT NULL DEFAULT '',
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES admin_user(id) ON DELETE SET NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS order_claim_item CASCADE;
DROP TABLE IF EXISTS order_claim CASCADE;
DROP TABLE IF EXISTS order_payment_method CASCADE;
DROP TABLE IF EXISTS order_payment_item CASCADE;
DROP TABLE IF EXISTS order_payment CASCADE;
DROP TABLE IF EXISTS order_list_print_log CASCADE;
DROP TABLE IF EXISTS order_shipping CASCADE;
DROP TABLE IF EXISTS order_list_item_warehouse CASCADE;
DROP TABLE IF EXISTS order_list_item CASCADE;
DROP TABLE IF EXISTS order_list CASCADE;
DROP TYPE IF EXISTS order_claim_status;
DROP TYPE IF EXISTS order_claim_payment_type;
DROP TYPE IF EXISTS order_payment_category;
DROP TYPE IF EXISTS order_list_print_kind;
DROP TYPE IF EXISTS order_shipping_type;
DROP TYPE IF EXISTS order_list_item_type;
DROP TYPE IF EXISTS order_list_item_status;
DROP TYPE IF EXISTS order_list_fulfill_status;
DROP TYPE IF EXISTS order_list_status;
-- +goose StatementEnd
