package order

import (
	"database/sql"

	"github.com/lMikadal/warehouse/backend/internal/config"
	"github.com/labstack/echo/v5"
)

func RegisterRoutes(g *echo.Group, db *sql.DB, cfg config.Config) {
	repo := NewCompareRepository(db)
	h := NewCompareHandler(repo)

	c := g.Group("/compares")
	c.GET("/tree", h.tree)
	c.GET("/rules", h.rules)
	c.PUT("/rules", h.putRules)
	c.GET("/export", h.export)
	c.POST("/import", h.importRules)

	formRead := NewSalesFormReadHandlers(db, cfg)

	storeRepo := NewStoreSalesRepository(db)
	storeH := NewStoreSalesHandler(storeRepo, formRead)
	s := g.Group("/store-sales")
	s.GET("", storeH.list)
	s.GET("/count", storeH.count)
	s.GET("/filters", storeH.filters)
	s.GET("/vat", formRead.ActiveVat)
	s.GET("/items", formRead.ListItems)
	s.GET("/members/:id", formRead.GetMember)
	s.POST("", storeH.create)
	s.GET("/:id", storeH.getByID)
	s.PATCH("/:id", storeH.update)
	s.PATCH("/:id/shipping", storeH.patchShipping)
	s.PATCH("/:id/status", storeH.patchStatus)
	s.DELETE("/:id", storeH.delete)

	qRepo := NewQuotationRepository(db)
	qH := NewQuotationHandler(qRepo, formRead)
	q := g.Group("/quotations")
	q.GET("", qH.list)
	q.GET("/count", qH.count)
	q.GET("/filters", qH.filters)
	q.GET("/vat", formRead.ActiveVat)
	q.GET("/items", formRead.ListItems)
	q.GET("/members/:id", formRead.GetMember)
	q.POST("", qH.create)
	q.GET("/:id", qH.getByID)
	q.PATCH("/:id", qH.update)
	q.PATCH("/:id/status", qH.patchStatus)
	q.POST("/:id/submit", qH.submit)
	q.POST("/:id/approve", qH.approve)
	q.POST("/:id/reject", qH.reject)
	q.POST("/:id/return", qH.returnForEdit)
	q.POST("/:id/accept", qH.accept)
	q.POST("/:id/payment", qH.payment)
	q.POST("/:id/picking", qH.picking)
	q.POST("/:id/fulfill-check", qH.fulfillCheck)
	q.POST("/:id/fulfill", qH.fulfill)
	q.POST("/:id/duplicate", qH.duplicate)
	q.DELETE("/:id", qH.delete)

	tRepo := NewTicketRepository(db)
	tH := NewTicketHandler(tRepo, storeRepo, formRead)
	t := g.Group("/tickets")
	t.GET("", tH.list)
	t.GET("/count", tH.count)
	t.GET("/filters", tH.filters)
	t.GET("/items", formRead.ListItems)
	t.GET("/members/:id", formRead.GetMember)
	t.POST("", tH.create)
	t.GET("/:id", tH.getByID)
	t.GET("/:id/history", tH.history)
	t.PUT("/:id", tH.update)
	t.PATCH("/:id/status", tH.patchStatus)
	t.PATCH("/:id/customer", tH.patchCustomer)
	t.PATCH("/:id/note", tH.patchNote)
	t.DELETE("/:id", tH.delete)
	t.POST("/:id/items", tH.createItem)
	t.PUT("/:id/items/:itemId", tH.updateItem)
	t.DELETE("/:id/items/:itemId", tH.deleteItem)
	t.PATCH("/:id/items/:itemId/status", tH.patchItemStatus)
	t.POST("/:id/items/:itemId/rejects", tH.createItemReject)
	t.PATCH("/:id/item-rejects/:rejectId/status", tH.patchItemRejectStatus)

	pRepo := NewPurchaseRepository(db)
	pH := NewPurchaseHandler(pRepo, storeRepo, formRead)
	p := g.Group("/purchases")
	p.GET("", pH.list)
	p.GET("/count", pH.count)
	p.GET("/filters", pH.filters)
	p.GET("/items", formRead.ListItems)
	p.GET("/stock-history", pH.stockHistory)
	p.POST("", pH.create)
	p.GET("/:id", pH.getByID)
	p.GET("/:id/history", pH.history)
	p.PUT("/:id", pH.update)
	p.PATCH("/:id/status", pH.patchStatus)
	p.PATCH("/:id/waiting", pH.patchWaiting)
	p.PUT("/:id/files", pH.putFiles)
	p.DELETE("/:id", pH.delete)
	p.POST("/:id/items", pH.createItem)
	p.PUT("/:id/items/:itemId", pH.updateItem)
	p.DELETE("/:id/items/:itemId", pH.deleteItem)
	p.PATCH("/:id/items/:itemId/status", pH.patchItemStatus)
	p.POST("/:id/items/:itemId/convert-unit", pH.convertItemUnit)
	p.POST("/:id/items/:itemId/revert-convert-unit", pH.revertItemUnit)
	p.GET("/:id/payments", pH.listPayments)
	p.POST("/:id/payments", pH.createPayment)
	p.DELETE("/:id/payments/:paymentId", pH.deletePayment)

	rcvRepo := NewReceiveRepository(db)
	rcvH := NewReceiveHandler(rcvRepo, pRepo, storeRepo, formRead)
	rc := g.Group("/receives")
	rc.GET("", rcvH.list)
	rc.GET("/count", rcvH.count)
	rc.GET("/filters", rcvH.filters)
	rc.GET("/bins", rcvH.bins)
	rc.GET("/:id", rcvH.getByID)
	rc.GET("/:id/history", rcvH.history)
	rc.GET("/:id/rejects", rcvH.rejects)
	rc.PUT("/:id/files", rcvH.putFiles)
	rc.GET("/:id/items/:itemId/placements", rcvH.placements)
	rc.POST("/:id/items/:itemId/receive", rcvH.receiveItem)
	rc.POST("/:id/items/:itemId/rejects", rcvH.createReject)
	rc.POST("/:id/items/:itemId/convert-unit", rcvH.convertItemUnit)
	rc.POST("/:id/items/:itemId/revert-convert-unit", rcvH.revertItemUnit)

	pickH := NewPickingHandler(NewPickingRepository(db), storeRepo, formRead)
	o := g.Group("/orders")
	o.GET("", pickH.list)
	o.GET("/count", pickH.count)
	o.GET("/filters", pickH.filters)
	o.GET("/vat", formRead.ActiveVat)
	o.GET("/items", formRead.ListItems)
	o.GET("/members/:id", formRead.GetMember)
	o.POST("", pickH.create)
	o.POST("/verify-credit", pickH.verifyCredit)
	o.POST("/verify-discount", pickH.verifyDiscount)
	o.GET("/:id/family", pickH.family)
	o.GET("/:id/payments", pickH.payments)
	o.POST("/:id/payments", pickH.createPayment)
	o.PATCH("/:id/payments/:paymentId", pickH.updatePayment)
	o.PATCH("/:id/status", pickH.patchStatus)
	o.PATCH("/:id/shipping", pickH.patchShipping)
	o.PATCH("/:id/items/:itemId", pickH.patchItem)

	storeClaimRepo := NewStoreClaimRepository(db)
	scH := NewStoreClaimHandler(storeClaimRepo, NewSalesClaimRepository(db), formRead)
	sc := g.Group("/store-claims")
	sc.GET("", scH.listPayments)
	sc.GET("/items", formRead.ListItems)
	sc.GET("/members/:id", formRead.GetMember)
	sc.GET("/:id", scH.getPayment)
	sc.GET("/:id/claims", scH.listClaims)
	sc.POST("/:id/claims", scH.createClaim)

	scl := g.Group("/store-claim-lists")
	scl.GET("", scH.list)
	scl.GET("/count", scH.count)
	scl.GET("/:id", scH.getDocument)
	scl.DELETE("/:id", scH.delete)

	salesClaimH := NewSalesClaimHandler(NewSalesClaimRepository(db))
	sa := g.Group("/sales-claims")
	sa.GET("", salesClaimH.list)
	sa.GET("/count", salesClaimH.count)
	sa.GET("/items", formRead.ListItems)
	sa.GET("/:id", salesClaimH.getByID)
	sa.PATCH("/:id/status", salesClaimH.patchStatus)
	sa.PATCH("/:id/items/:itemId", salesClaimH.patchItem)
	sa.DELETE("/:id", salesClaimH.delete)

	clmH := NewClaimHandler(NewClaimRepository(db), pRepo)
	cl := g.Group("/claims")
	cl.GET("", clmH.list)
	cl.GET("/count", clmH.count)
	cl.GET("/:id", clmH.getByID)
	cl.GET("/:id/history", clmH.history)
	cl.PUT("/:id", clmH.update)
}
